"""Print src/signatures.ts from the Python reference engine's function signatures.

    python3 app/packages/engine/scripts/signatures.py > app/packages/engine/src/signatures.ts

`make app-check` diffs this output against the committed file, so a function added to
tools/rules_engine.py fails the check until the TypeScript engine has it too.
"""

import inspect
import json
import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "tools"))
import rules_engine as E  # noqa: E402

sigs = {
    name: list(inspect.signature(fn).parameters)
    for name, fn in inspect.getmembers(E, inspect.isfunction)
    if fn.__module__ == "rules_engine" and not name.startswith("_")
}

print("// Generated by scripts/signatures.py from tools/rules_engine.py. Do not edit.")
print("// Each Python function and its parameter names, in order: the fixtures pass arguments by")
print("// these names, and the Engine method is the name in camelCase.")
print("export const SIGNATURES: Record<string, readonly string[]> = {")
for name, params in sigs.items():
    print(f"  {name}: {json.dumps(params)},")
print("};")
